// <auto-generated />
namespace OHD_Project_Sem_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateee));
        
        string IMigrationMetadata.Id
        {
            get { return "202003131913506_updateee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
