// <auto-generated />
namespace OHD_Project_Sem_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitializeDatabasenew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitializeDatabasenew));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111506343_InitializeDatabase-new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
